apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: docs
  namespace: ${KUBE_NAMESPACE}
spec:
  replicas: 2
  minReadySeconds: 10
  revisionHistoryLimit: 10
  strategy:
    type: 'RollingUpdate'
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 5
  template:
    metadata:
      labels:
        app: docs
      annotations:
        commit: ${COMMIT_HASH}
    spec:
      restartPolicy: Always
      containers:
        - name: ${APP_NAME}
          image: ${DOCKER_IMAGE}:${DOCKER_TAG}
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
          - containerPort: 80
            name: http
