# Default values for docs.
# This is a YAML-formatted file.
replicaCount: 1
image:
  repository: gcr.io/exponentjs/exponent-docs-v2-staging
  tag: ac145935cb76c338285ffe9b1d4abddf3f8c4dfc
gitCommit: ""
ingress: []
service:
  externalPort: 80
  internalPort: 80
resources:
  requests:
    cpu: 200m
    memory: 256Mi
